#!/usr/bin/bash

PYTHONPATH="..:$PYTHONPATH" \
    systemd-run \
        --user \
        --scope \
        --property MemoryAccounting=1 \
        --property MemoryMax=35G \
    python "$1/day${1#0}.py"

