#!/usr/bin/bash

PYTHONPATH="../..:$PYTHONPATH" \
    systemd-run \
        --user \
        --scope \
        --property MemoryAccounting=1 \
        --property MemoryMax=35G \
    python -m "day$1"

