#!/usr/bin/bash

DIR="$1"
YEAR=$( basename $PWD )
if [ -d "$DIR" ];
then
    echo "$DIR already exists"
else
    mkdir $DIR
    touch ../input/$YEAR/$DIR/example
    cp ../aocl/stub.py $DIR/"day${1#0}".py
fi
